version: 2.1

orbs:
    hello: circleci/hello-build@volatile

commands:
    sayhello:
        description: "A very simple command for demonstration purposes"
        parameters:
            to:
              type: string
              default: "Hello World"
        steps:
            - run: echo Hello, << parameters.to >>

executors:
    node-env:
        docker:
            - image: "circleci/node:9.6.1"
        environment:
            - NAME: Shingo

jobs:
    greeting:
        executor: node-env
        steps:
            - sayhello:
                to: ${NAME}

workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
          - greeting